# Generated by Django 5.1.3 on 2024-11-14 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='author',
            index=models.Index(fields=['last_name', 'first_name'], name='blogs_autho_last_na_f989fa_idx'),
        ),
    ]
