# Generated by Django 5.1.3 on 2024-11-14 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0002_author_blogs_autho_last_na_f989fa_idx'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='num_of_stars',
            field=models.IntegerField(choices=[(1, 'Very Bad'), (2, 'Bad'), (3, 'Good'), (4, 'Very Good'), (5, 'Perfect')]),
        ),
    ]
